services:
  jina-openai:
    build:
      context: ./app
    container_name: jina-openai
    deploy:
      resources:
        limits:
          cpus: '4.0'
    ports:
      - "4000:8082"
    environment:
      - MODEL_NAME=jinaai/jina-embeddings-v2-base-code
      - JINA_TELEMETRY_OPTOUT=1
      - MICRO_BATCH_SIZE=8
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8082/health"]
      interval: 30s
      timeout: 25s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  warmup:
    image: curlimages/curl:8.8.0
    depends_on:
      jina-openai:
        condition: service_healthy
    entrypoint: ["/bin/sh","-lc"]
    command: >
      sh -c 'curl -fsS -X POST http://jina-openai:8082/v1/embeddings -H "Content-Type: application/json" -d "{\"model\":\"jina-code-v2\",\"input\":[\"warmup\"]}" >/dev/null && echo warmup-ok'
    restart: "no"
